In [1]:
x=5
y=6
print(x+y)

11


In [2]:
print("my " + my_string + " is level " + str(x))


NameError: name 'my_string' is not defined

In [3]:
my_string="python"
print("my " + my_string + " is level " + str(x))


my python is level 5


In [10]:
my_string.upper()
my_string.find("y")


1

In [16]:
colors = ["red", "blue", "green"]
colors.pop(1)
print(colors)
colors.index("green")

['red', 'green']


1

In [18]:
primes=[2,3,5,7]
for prime in primes:
    print (prime)

2
3
5
7


In [19]:
my_tuple = ("price", 5.7)
print(len(my_tuple))
print(my_tuple[1])

2
5.7


In [20]:
import numpy as np
import pandas as pd
import scipy

In [22]:
col_vec=np.array([[1],[2]])
print (col_vec)

[[1]
 [2]]


In [23]:
row=np.array([1,2])
print(row)

[1 2]


In [29]:
matrix=np.array([[1,2,5],[3,4,6]])
print(matrix)

[[1 2 5]
 [3 4 6]]


In [30]:
shape=matrix.shape
print("matrix rows",shape[0],"columns",shape[1])

matrix rows 2 columns 3


In [33]:
my_matrix_t = matrix.transpose()
print ("transposed matrix")
print (my_matrix_t)

transposed matrix
[[1 3]
 [2 4]
 [5 6]]


In [34]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print( a + b)

[[ 6  8]
 [10 12]]


In [36]:
print(np.dot(a,b))

[[19 22]
 [43 50]]


In [40]:
array = np.array([1, 2, 2, 4, 5])
len(array)
array.sum()
np.unique(array)

array([1, 2, 4, 5])

In [42]:
array[-1]
array[array>2]

array([4, 5])

In [52]:
np.delete(array,[3])


array([1, 2, 2, 5])

In [ ]:
pandas

In [55]:
df = pd.DataFrame(
    {
        "customer_id": ["A", "B", "C"],
        "date": ["5/1/2017", "5/8/2017", "5/11/2017"],
        "spend": [10, 5, 20]
    },
    index = [1, 2, 3],
    columns = ["customer_id", "date", "spend"]
)
print(df)

  customer_id       date  spend
1           A   5/1/2017     10
2           B   5/8/2017      5
3           C  5/11/2017     20


In [63]:
df.shape
df["spend"]
df.sample(n = 1)
df.head(n = 2)

customer_id      date  spend
1           A  5/1/2017     10
2           B  5/8/2017      5

In [64]:
file_location = "/Users/jingwan/Downloads/"
file_name = "BA501_python_data.csv"
my_data = pd.read_csv(file_location + file_name)

my_data.head(5)

country      date  experiment_id              order_id  spend_usd  \
0      JP  20170402       12624548   5813140433216629693  16.138855   
1      US  20170403       12624549  16333056276711034931   9.990000   
2      JP  20170404       12624548  11227119161741298366  19.887087   
3      US  20170403       12624548  11927299833124210932  19.990000   
4      JP  20170403       12624549  11644727017708872749  88.220093   

                user_id      vertical  
0   5006730028073359543  ANDROID_APPS  
1   5938685669571545259  ANDROID_APPS  
2  17623708458399141713  ANDROID_APPS  
3  18042812344456618148  ANDROID_APPS  
4   4325104700699531031  ANDROID_APPS

In [78]:
#my_data[["user_id","date","spend_usd"]].head(5)
my_data["user_id"].head(5)
np.unique(my_data["country"]).head(5)


TypeError: unorderable types: str() > float()

In [97]:
my_data[1:10]
my_data[(my_data.vertical == 'MUSIC') & (my_data.country == "JP")]
my_data[["user_id","date","spend_usd"]][(my_data.vertical == 'MUSIC') & (my_data.country == "JP")]
my_data['spend_usd_whole'] = my_data['spend_usd']*5
my_data.head(5)
my_data = my_data.drop("spend_usd_whole", axis = 1)
my_data.head(5)
my_data.date = pd.to_datetime(my_data.date, format='%Y%m%d')
my_data.head(4)

country       date  experiment_id              order_id  spend_usd  \
0      JP 2017-04-02       12624548   5813140433216629693  16.138855   
1      US 2017-04-03       12624549  16333056276711034931   9.990000   
2      JP 2017-04-04       12624548  11227119161741298366  19.887087   
3      US 2017-04-03       12624548  11927299833124210932  19.990000   

                user_id      vertical  
0   5006730028073359543  ANDROID_APPS  
1   5938685669571545259  ANDROID_APPS  
2  17623708458399141713  ANDROID_APPS  
3  18042812344456618148  ANDROID_APPS

In [105]:
#result = my_data.groupby(["country"])["spend_usd"].sum()
result = my_data.groupby(["country"])["spend_usd"].sum().reset_index()
#result = result.set_index("country")
result
my_data = my_data.sort_values(['country','date'],ascending=[True, True])
my_data.head(5)

country       date  experiment_id              order_id  spend_usd  \
15381      AE 2017-04-03       12624548   8078410735682954089   1.984784   
22250      AE 2017-04-04       12624549   6754390085836948239   0.977429   
19088      AE 2017-04-05       12624549  13528583286475944786  10.071074   
38119      AE 2017-04-05       12624548  18081415353723908788   0.952926   
22092      AE 2017-04-07       12624549  18156435304744752611   0.977428   

                    user_id      vertical  
15381  15342218896746506117  ANDROID_APPS  
22250  11276568206142884528  ANDROID_APPS  
19088  10187980296635197684  ANDROID_APPS  
38119    921275339006250633  ANDROID_APPS  
22092   5956003464692123193  ANDROID_APPS